### ISSUE TITLE
Q4 kontent kedd material

### ISSUE THREAD

**Issue by herflis** [SenseNet/docs.sensenet.com#113]
### Tutorials
- [x] getting started .net client
- [x] getting started react
- [x] getting started next js
- [x] authentication net client
- [x] authentication react

### Concepts 
- [x] authentication
- [ ] secrets (about access tokens, generation, how to use them, in general)

### Api docs
- [ ] authentication/secrets (API examples for using tokens,  for getting the tokens, regenerate tokens)

### Blogposts
- [x] sn.com (Cs)
- [ ] sn containerization 
- [ ] webhooks
- [x] hacktoberfest 1
- [x] hacktoberfest 2
- [x] hacktoberfest 3
- [x] sncom case study (a)
- [ ] advanced search

### Concepts
- [ ] Built-in content types
   - [ ] Generic content
   - [ ] Folder
   - [ ] User
   - [ ] Group
   - [ ] Organizational unit
   - [x] File (M)
   - [x] Image (M)
   - [ ] ContentList
   - [ ] DocumentLibrary
   - [ ] ImageLibrary
   - [ ] MemoList
   - [ ] TaskList
   - [x] Workspace (E) -- Need to be extended
   - [x] Task (E)  -- Need to be extended
   - [x] Memo (E)  -- Need to be extended
   - [x] SmartFolder (E)  -- Need to be extended
   - [x] Article (E)  -- Need to be extended
   - [x] LinkList (E)
   - [x] ContentLink (E)
   - [x] Link (E)
   - [x] EventCalendar (E)
   - [x] CalendarEvent (E)
- Fields
   - [x] field setting
   - [x] field indexing
   - [x] field controls
   - [x] ShortText
   - [x] LongText
   - [x] Integer
   - [x] Number
   - [x] Boolean
   - [x] Choice
   - [x] Reference
   - [x] DateTime
   - [x] HyperLink
   - [x] Image
   - [x] Binary

### Integrations
- [google anatylics](https://docs.kontent.ai/tutorials/develop-apps/integrate/google-analytics)
- [https://kontent.ai/blog/using-slack-webhooks-with-kentico-cloud](https://kontent.ai/blog/using-slack-webhooks-with-kentico-cloud)
- gatsby
- nextjs
