### ISSUE TITLE
Q1 kontent kedd material

### ISSUE THREAD

**Issue by herflis** [SenseNet/docs.sensenet.com#155]
### Tutorials
- [x] getting started with MVC and sensenet

### Concepts 
- [x] secrets (about access tokens, generation, how to use them, in general)
- [x] webhooks

### Blogposts
- [x] docviewer (E | jan)
- [x] webhooks (M | feb)
- [x] collaboration (A)

### Concepts
- [x] Built-in content types 
   - [x] Generic content (E) -- Content handler description and features are missing
   - [x] Folder (E) -- Content handler description and features are missing
   - [x] User (E) -- OK
   - [x] Group (E) -- Content handler description and features are missing
   - [x] Organizational unit (E) -- Content handler description and features are missing
   - [x] File (M)  -- Content handler description is missing
   - [x] Image (M)  -- Content handler description is missing
   - [x] ContentList (E) -- Content handler description and features are missing
   - [x] DocumentLibrary (E) -- Content handler description and features are missing
   - [x] ImageLibrary (E) -- Content handler description and features are missing
   - [x] MemoList (E) -- Content handler description and features are missing
   - [x] TaskList (E) -- Content handler description and features are missing
   - [x] Workspace (E) -- Content handler description and features are missing
   - [x] Task (E)  -- Content handler description and features are missing
   - [x] Memo (E)  --Content handler description and features are missing
   - [x] SmartFolder (E)  -- Content handler description and features are missing
   - [x] Article (E)  --Content handler description and features are missing
   - [x] LinkList (E) -- Content handler description is missing
   - [x] ContentLink (E) -- Content handler description is missing
   - [x] Link (E) -- Content handler description is missing
   - [x] EventCalendar (E) -- Content handler description is missing
   - [x] CalendarEvent (E) -- Content handler description is missing

### Guides
- [x] docviewer editor stuff (E) https://github.com/SenseNet/docs.sensenet.com/pull/192
- [x] copy/move with picker
