### ISSUE TITLE
Q3 kontent kedd material

### ISSUE THREAD

**Issue by herflis** [SenseNet/docs.sensenet.com#63]
### Blogposts
- [x] The new docs site
- [x] permission editor (E) --> https://github.com/SenseNet/sensenet.github.io/pull/444

#### Drawer+header
- [x] login with business cat -> 7 menuitem (E) --> https://github.com/SenseNet/sn-client/issues/744
- [x] login with devdog -> 7 menuitem (E) --> https://github.com/SenseNet/sn-client/issues/744
- [x] login with eidtormanatee -> 2 menuitem (E)  --> https://github.com/SenseNet/sn-client/issues/744
- [x] open drawer (CS)
- [x] close drawer (CS)
- [x] click on search (Z)
- [x] click on content (Z)
- [x] click on u&g (Z)
- [x] click on trash (Z)
- [x] click on content types (Z)
- [x] click on localization (Z)
- [x] click on setup (Z)
- [x] switch to dark theme (A)
- [x] default theme is light (A)
- [x] click on the logo in the header (E) -->https://github.com/SenseNet/sn-client/issues/828
- [x] drawer item active state
- [x] breadcrumb [https://github.com/SenseNet/sn-client/issues/796](https://github.com/SenseNet/sn-client/issues/796)
   - [x] display breadcrumb (A)
   - [x] navigate to a parent with breadcrumb (A)
   - [x] breadcrumb right-click/contextmenu (A)
- [x] open the addnew menu (E)
- [x] choose something from the addnew menu (E) --> https://github.com/SenseNet/sn-client/issues/776
- [x] disabled addnew button when new view is active (E)  --> https://github.com/SenseNet/sn-client/issues/776
- [x] tree (E) --> https://github.com/SenseNet/sn-client/issues/793
   - [x] opening a treeitem (E)
   - [x] closing a tree item (E)
   - [x] tree contextmenu (E)  
- [x] using setup menu (E) --> https://github.com/SenseNet/sn-client/issues/794
   - [x] right click actionmenu (E)
   - [x] using edit button (E)
   - [x] using 'learn more' button (E)
- [x] using localization menu (E) --> https://github.com/SenseNet/sn-client/issues/795
   - [x] ActionResources.xml is there in the list (E)
   - [x] right click actionmenu (E)
   - [x] dbl-click (E)
- [x] using content type menu (E) --> https://github.com/SenseNet/sn-client/issues/829 
   - [x] Article is there in the list (E)
   - [x] right click actionmenu (E) //TODO: check if it changes
   - [x] dbl-click (E)
- [x] add custom filetypes: (E) --> https://github.com/SenseNet/sn-client/issues/906
   - [x] add new contenttype (E)
   - [x] add new string resources (E)
   - [x] add new settings file (E)
- [x] users (E) --> https://github.com/SenseNet/sn-client/issues/907
   - [x] open u&g (E)
   - [x] columns (E)
   - [x] right click actionmenu (E)
   - [x] dblclick (E)
- [x] user enabled field (E) --> https://github.com/SenseNet/sn-client/issues/914
- [x] groups (E) -->https://github.com/SenseNet/sn-client/issues/908
    - [x] switch to groups (E)
    - [x] check columns (E)
    - [x] right click actionmenu (E)
    - [x] dblclick (E)
- [x] role/member editor (E) --> https://github.com/SenseNet/sn-client/issues/909
   - [x] autocomplete (E)
   - [x] add a user (E)
   - [x] remove a user (E)
- [x] org units [https://github.com/SenseNet/sn-client/issues/798](https://github.com/SenseNet/sn-client/issues/798)
   - [x] add org unit (A)
   - [x] tree (A)
- [x] add u&g [https://github.com/SenseNet/sn-client/issues/797](https://github.com/SenseNet/sn-client/issues/797)
   - [x] add user (A)
   - [x] add group (A)
- [x] batch operations (E) --> https://github.com/SenseNet/sn-client/issues/830
   - [x] delete batch (E)
   - [x] move batch (E)
   - [x] copy batch (E)
- [x] header & dashboard (E) -->https://github.com/SenseNet/sn-client/issues/911
   - [x] header repourl (E)
   - [x] subscription plan info (E)
   - [x] usage (E)
- [X] permission editor main screen lists (E) --> https://github.com/SenseNet/sn-client/issues/861
- [X] permission editor main screen links (E) --> https://github.com/SenseNet/sn-client/issues/862
- [X] permission editor dialog buttons (E) --> https://github.com/SenseNet/sn-client/issues/886
- [X] permission editor force relations and group switcher (E) --> https://github.com/SenseNet/sn-client/issues/887
- [X] add new permission entry (E) --> https://github.com/SenseNet/sn-client/issues/865
- [X] public/private content (E) --> https://github.com/SenseNet/sn-client/issues/864
- [X] editing group member in permission editor (E) --> https://github.com/SenseNet/sn-client/issues/866
- [X] set a permission local only (E) --> https://github.com/SenseNet/sn-client/issues/867
- [X] permission.settings modification (E) --> https://github.com/SenseNet/sn-client/issues/888
- [x] create/delete content (E) --> https://github.com/SenseNet/sn-client/issues/915
- [x] edit content (E) --> https://github.com/SenseNet/sn-client/issues/916
- [x] upload (E) --> https://github.com/SenseNet/sn-client/issues/917
- [X] version history (E) --> https://github.com/SenseNet/sn-client/issues/919
   - [x] restore
- [x] docviewer (A)
   - [x] open docviewer
   - [x] scrolling
   - [x] jump to page
- [x] docviewer thumbnails (A)
   - [x] thumbnails open/close
   - [x] click to thumbnail
   - [x] scroll thumbnails
- [x] docviewer zoom in docviewer (A)
   - [x] zoom in
   - [x] zoom out
- [x] docviewer rotate pages and doc (A)
   - [x] rotate right
   - [x] rotate doc right
   - [x] rotate right on thumbnails
- [x] docviewer comments (A)
   - [x] toggle comment box
   - [x] add comment
   - [x] delete comment
- [x] versioning (E)
   - [x] versioning with Major and minor versioning mode (E) --> https://github.com/SenseNet/sn-client/issues/927
   - [x] versioning with Major only versioning mode (E) --> https://github.com/SenseNet/sn-client/issues/928
   - [x] content change without versioning (E) --> https://github.com/SenseNet/sn-client/issues/929
- [X] approval (E)
   - [x] version approval (E) --> https://github.com/SenseNet/sn-client/issues/930
   - [x] version rejection (E) --> https://github.com/SenseNet/sn-client/issues/931
- [x] trash+restore (E) --> https://github.com/SenseNet/sn-client/issues/932
- [x] saved queries (E) --> https://github.com/SenseNet/sn-client/issues/935
- [ ] allowed childtypes
- [ ] grid keyboard shortcuts (Anikó u are the queen in this topic 👸 👑 )
- [x] grid contextmenu (E) --> https://github.com/SenseNet/sn-client/issues/938
- [x] grid ordering (E) --> https://github.com/SenseNet/sn-client/issues/942
- [x] custom drawer item (E) --> https://github.com/SenseNet/sn-client/issues/943
- [x] calendar event content (E) --> https://github.com/SenseNet/sn-client/issues/950
   - [x] create (E)
   - [x] edit (E)
   - [x] delete (E)
- [x] file content (E) --> https://github.com/SenseNet/sn-client/issues/951
   - [x] create (E)
   - [x] edit (E)
   - [x] delete (E)
- [x] link content (E) --> https://github.com/SenseNet/sn-client/issues/952
   - [x] create (E)
   - [x] edit (E)
   - [x] delete (E)
- [x] memo content (E) --> https://github.com/SenseNet/sn-client/issues/953
   - [x] create (E)
   - [x] edit (E)
   - [x] delete (E)
- [x] task content (E) -->https://github.com/SenseNet/sn-client/issues/954
   - [x] create (E)
   - [x] edit (E)
   - [x] delete (E)
- [x] query content (E) -->https://github.com/SenseNet/sn-client/issues/956
   - [x] create (E)
   - [x] edit (E)
   - [x] delete (E)
- [x] document library content (E) -->https://github.com/SenseNet/sn-client/issues/957
   - [x] create (E)
   - [x] edit (E)
   - [x] delete (E)
- [x] memo list content (E) -->https://github.com/SenseNet/sn-client/issues/958
   - [x] create (E)
   - [x] edit (E)
   - [x] delete (E)
- [x] link list content (E) -->https://github.com/SenseNet/sn-client/issues/959
   - [x] create (E)
   - [x] edit (E)
   - [x] delete (E)

**Comment by taki9** [comment]
List field removal is not filled in the documentation for react and sn-client, because:
- DeleteField action currently not working in .NET core environments.
- SenseNet JS API currently give no option to create requests with DELETE method.

**Comment by herflis** [comment]
### Another findings:

**https://docs.sensenet.com/concepts/introduction**

If I reach this page from the exact url drawer lose its active style

**https://docs.sensenet.com/concepts/basics/04-search**

Metadata indexing, searching by fields --> What is this [link] for?

**https://docs.sensenet.com/concepts/content-management/02-content-model**

It seems that it is not finished.

**https://docs.sensenet.com/concepts/content-management/03-content-types**

(see How to create a Content Type for details) this link is not yet valid

**https://docs.sensenet.com/concepts/content-management/031-fields**

Integer field is empty (has no description)

**https://docs.sensenet.com/concepts/collaboration**

This is empty, it has no contents

**https://docs.sensenet.com/concepts/collaboration/03-office-online-editing**

sensenet enables collaborative content management, thanks to Office Online editing among others.

Is this link needed? Cause it link to the page itself after my change. It was an invalid link before.

**https://docs.sensenet.com/concepts/collaboration/06-sharing**

Sharing FAQ

There is no aswer for the first question: What happens when something that is related to a shared content or a user changes?

**https://docs.sensenet.com/concepts/user-and-permission-management**

This is empty, it has no contents

**https://docs.sensenet.com/concepts/client-side-forms**

[illustration of a custom content type with questions as fields] is missing

**https://docs.sensenet.com/concepts/webhooks**

This is empty, it has no contents

**https://docs.sensenet.com/concepts/logging**

This is empty, it has no contents
